import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import MainWrapper from "@/components/MainWrapper";

const outfitFont = Outfit({
  variable: '--font-outfit',
  subsets: ['latin'], // You can add other subsets if needed
  weight: ['300', '400', '500', '600', '700'], // Add weights you plan to use
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfitFont.variable} antialiased`}
      >
        <MainWrapper>{children} </MainWrapper>
      </body>
    </html>
  );
}
